/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArtigosQuickMassageRouteImport } from './routes/artigos.quick-massage'
import { Route as ArtigosRetencaoTalentosRouteImport } from './routes/artigos.retencao-talentos'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtigosQuickMassageRoute = ArtigosQuickMassageRouteImport.update({
  id: '/artigos/quick-massage',
  path: '/artigos/quick-massage',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtigosRetencaoTalentosRoute = ArtigosRetencaoTalentosRouteImport.update({
  id: '/artigos/retencao-talentos',
  path: '/artigos/retencao-talentos',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/artigos/quick-massage': typeof ArtigosQuickMassageRoute
  '/artigos/retencao-talentos': typeof ArtigosRetencaoTalentosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/artigos/quick-massage': typeof ArtigosQuickMassageRoute
  '/artigos/retencao-talentos': typeof ArtigosRetencaoTalentosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/artigos/quick-massage': typeof ArtigosQuickMassageRoute
  '/artigos/retencao-talentos': typeof ArtigosRetencaoTalentosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/artigos/quick-massage' | '/artigos/retencao-talentos'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/artigos/quick-massage' | '/artigos/retencao-talentos'
  id: '__root__' | '/' | '/artigos/quick-massage' | '/artigos/retencao-talentos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArtigosQuickMassageRoute: typeof ArtigosQuickMassageRoute
  ArtigosRetencaoTalentosRoute: typeof ArtigosRetencaoTalentosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artigos/quick-massage': {
      id: '/artigos/quick-massage'
      path: '/artigos/quick-massage'
      fullPath: '/artigos/quick-massage'
      preLoaderRoute: typeof ArtigosQuickMassageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artigos/retencao-talentos': {
      id: '/artigos/retencao-talentos'
      path: '/artigos/retencao-talentos'
      fullPath: '/artigos/retencao-talentos'
      preLoaderRoute: typeof ArtigosRetencaoTalentosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArtigosQuickMassageRoute: ArtigosQuickMassageRoute,
  ArtigosRetencaoTalentosRoute: ArtigosRetencaoTalentosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
